# Generated by Django 6.0.3 on 2026-03-26 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_return_date__gte", models.F("borrow_date"))
                ),
                name="expected_return_after_borrow_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_return_date__isnull", True),
                    ("actual_return_date__gte", models.F("borrow_date")),
                    _connector="OR",
                ),
                name="actual_return_after_borrow_date",
            ),
        ),
    ]
